name: Run Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '1 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Replace Webhook
      run: |
        SECRET=$(echo "${{ secrets.WEBHOOK_SECRET }}" | sed -e 's/[\/&]/\\&/g') \
        echo "The value of the secret is $SECRET" \
        && sed -i "s|URL_PLACEHOLDER|$SECRET|g" notifier.py \
        && cat notifier.py

    - name: Run Notifer
      run: python notifier.py
