name: Run Notifier

on:
  workflow_dispatch:
  schedule:
    - cron: '1 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Replace Webhook
      env:
      run: |
        echo ${{ env.WEBHOOK_URL }} \
        && sed -i 's|URL_PLACEHOLDER|'"${{ env.WEBHOOK_URL }}"'|g' notifier.py \
        && cat notifier.py

    - name: Run Notifer
      run: python notifier.py
